# filepath: /home/coydog16/flask/navStupro/docker-compose.yml
version: '3.8'

services:
  # マルチステージビルドを使用した統合開発環境
  devenv:
    build:
      context: .
      dockerfile: ./docker/builder/Dockerfile
      # builderステージではなくdevenvステージをターゲットに
      target: devenv
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    volumes:
      # プロジェクトのルートディレクトリをマウント
      - ./:/workspace:delegated,z
      # node_modulesをボリュームにマウント（キャッシュのため）
      - frontend_node_modules:/workspace/app/frontend/node_modules
    ports:
      - "3000:3000" # フロントエンド開発サーバー
      - "5000:5000" # バックエンド開発サーバー
    environment:
      - NODE_ENV=development
      - FLASK_APP=app/backend/app/app.py
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://navStupro:navStupro@db:5432/navstupro
      - PYTHONPATH=/workspace/app/backend
    tty: true
    stdin_open: true
    command: sh -c "tail -f /dev/null"
    depends_on:
      - db
    networks:
      - navstupro

  # データベース - PostgreSQL
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/pgsql/logs:/var/log
    environment:
      - POSTGRES_USER=navStupro
      - POSTGRES_PASSWORD=navStupro
      - POSTGRES_DB=navstupro
      - PGPASSWORD=navStupro
      - TZ=Asia/Tokyo
    ports:
      - "5432:5432"
    networks:
      - navstupro
      
  # 開発用DB管理ツール - pgAdmin 4
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - navstupro

networks:
  navstupro:
    driver: bridge

volumes:
  postgres_data:
  frontend_node_modules:
  pgadmin_data:
