services:
  backend:
    build:
      context: ./docker/backend
    volumes:
      - ./app/backend:/app
    expose:
      - "5000"
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    command: sh -c "pip install -r requirements.txt && flask run --host=0.0.0.0"

  frontend:
    build:
      context: ./docker/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - PORT=3000
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    command: sh -c "npm install && npm run dev -- --host"

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./app/backend:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

  postgres:
    build:
      context: ./docker/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - ./db/pgsql/data:/var/lib/postgresql/data
      - ./db/pgsql/logs:/var/log

  # 開発用ツール
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
