"""add avatar_image_id to user and create images table

Revision ID: 6cc1108a3f83
Revises: 98471de55562
Create Date: 2025-05-29 15:15:20.088134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc1108a3f83'
down_revision = '98471de55562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_image_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_avatar_image_id_images', 'images', ['avatar_image_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_avatar_image_id_images', type_='foreignkey')
        batch_op.drop_column('avatar_image_id')

    op.drop_table('images')
    # ### end Alembic commands ###
